// GENERATED BY CODE! DO NOT MODIFY!
namespace Watermelon
{
	public partial class PrefsSettings
	{
		public enum Key
		{
			Vibration = 0,
			Volume = 1,
			HighScore = 2,
			AdsSkinUnlockProgress = 3,
			IsShareSkinUnlocked = 4,
		}
	}
}