// GENERATED BY CODE! DO NOT MODIFY!
using UnityEngine;
namespace Watermelon
{
	[System.Serializable]
	public class Sounds
	{
        public AudioClip buttonSound;
        public AudioClip defaultHitSound;
        public AudioClip jumpPlatformSound;
        public AudioClip energyFieldSound;
        public AudioClip boosterSound;
        public AudioClip invisiblePlatformSound;
        public AudioClip powerUpPickUp;
        public AudioClip portalSound;
        public AudioClip gameOverSound;
        public AudioClip wilhelmScream;
    }
}